groups:
  - name: DemoAlerts
    rules:
      - alert: AppFastAPIDown
        expr: up{job="app"} < 1 
        for: 1m
        labels:
          severity: low
        annotations:
          summary: 'App Fast api está down verificar.'

      - alert: NodeExporterDown
        expr: up{job="node"} < 1 
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: 'Node Exporter está down verificar.'

      - alert: TargetsDown
        expr: count(up == 0) > 1 
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Existem targets down verificar.'

      - alert: TargetsDownNovo
        expr: count(up == 0) > 1 
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Existem targets down verificar.'

      - alert: Uptime
        expr: (node_time_seconds - node_boot_time_seconds) /60  < 30
        for: 1m
        labels:
          severity: high
        annotations:
          summary: 'A maquina reiniciou nos ultimos 30min.'



