{
 "title": "Historico de Alertas Oficina",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Historico de Alertas",
   "type": "bargauge",
   "description": "Historico de alertas ocorridos em um determinado periodo selecionado.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (alertname,severity) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) + (count by (alertname,severity) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) * 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "historico de Alertas por Tempo",
   "type": "timeseries",
   "description": "Historico de Alertas ocorridos no grafico Time Series durante o periodo selecionado.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (alertname) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) + (count by (alertname) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) * 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "historico de Alertas por Severidade",
   "type": "timeseries",
   "description": "Historicos de Alertas durante o periodo de tempo selecionado por Severidade",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (severity) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) + (count by (severity) (changes(ALERTS_FOR_STATE[$__range]) AND ignoring(alertstate) max_over_time(ALERTS{alertstate=\"firing\"}[$__range])) * 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertas Ativos no Momento",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alertas Silenciados",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {}
   ]
  }
 ]
}