
global:
  slack_api_url: 'https://hooks.slack.com/services/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'  


templates: 
- '/etc/prometheus/alertmanager_templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service','instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h 
  receiver: 'monitoramento-alertas'
  routes:
  - matchers:
    - severity=~"critical|high"
    receiver: 'monitoramento-criticos'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']

receivers:
- name: 'monitoramento-alertas'
  slack_configs:
  - channel: '#alertas-nao-criticos'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} para {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alerta:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Descrição:* {{ .Annotations.description }}

     *Detalhes:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}

- name: 'monitoramento-criticos'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#alertas-criticos'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} para {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alerta:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Descrição:* {{ .Annotations.description }}

     *Detalhes:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
